<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test suites consisting of all available post APIs</description>
   <name>TS POST APIs</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>046c354a-a63e-4675-b3d7-9d6936d498a3</testSuiteGuid>
   <testCaseLink>
      <guid>5b809059-111c-466f-8c01-a69b35c3be6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST APIs/POST create a user</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>239295ca-9adb-46e8-bab9-9e373ad7af4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>887f42a4-5ed3-4119-a744-08780ad8ec5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83b407b7-4b01-48c0-ab2e-6f5af5231b2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST APIs/POST Login Successful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>feda6f81-7b6a-487f-9008-16f995b636fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST APIs/POST Login Unsuccessful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ee68966c-689a-4f57-b712-94c19d1641cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST APIs/POST Register Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e30e1f-8385-4d91-a298-9c8aefd9ad50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce4d8454-9eda-467b-8c0d-c407be4029fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27d9ff4f-ef1b-4899-a066-f031ac43c4d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f050aac0-0d44-471d-aa67-5f6eecc29ee4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST APIs/POST Register unsuccessful - empty email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f381abb-a781-4e43-8e77-11f95126ab9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17fb721f-7294-4d10-b049-c81650ac1f8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03e61f14-38fa-4406-b40a-1ea3d9f8b5f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0751f6d3-5b8d-4a89-b9b8-82c8a140dde0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST APIs/POST Register unsuccessful - empty password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>469ead9e-6cbe-4c86-820b-340bfd5d5309</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad02c973-e3ba-4bd6-9d8a-7ea1aa026d76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c141721c-adea-4e21-ab17-a8e42eff46c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cee08bcf-3772-44fc-8bdb-c0994fb0ce82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POST APIs/POST Register unsuccessful - unpredefined email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0702fe02-69ba-439d-87ad-bf7dcbd00730</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8735742b-ac41-4ffb-b953-f9793cca899a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
